site_name: ClusterCockpit Setup Guide
repo_url: https://git-ce.rwth-aachen.de/hpc.nrw/ap3/energieeffizienter-betrieb/cc-setup-guide
repo_name: hpc.nrw/ap3/energieeffizienter-betrieb/cc-setup-guide
#site_url: https://git-ce.rwth-aachen.de/hpc.nrw/ap3/energieeffizienter-betrieb/cc-setup-guide

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark theme
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light theme
  features:
    # Navigation & Struktur
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - navigation.tracking
    # Inhaltsverzeichnis
    - toc.integrate
    - toc.follow
    # Suche & Inhalte
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    # Header-UX
    - header.autohide

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      lang:
        - en
        - de
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          name: English
          build: true
          default: true
          nav:
            - Introduction: index.md
            - Server Preparation: system_preparation.md
            - Monitoring Server: monitoringserver.md
            - Webinterface: webinterface.md
            - Create First Cluster & Define Subcluster: cluster_setup.md
            - Metrics and Collectors:
                - Set Up cc-metric-collector: cc_metric_collector_setup.md
                - Quick Setup (Fast Track): cc_metric_collector_quicksetup.md
                - Step-by-step Guides:
                    - Step-by-step First Metric: metrics.md
                    - Step-by-step Additional Metrics: more_metrics.md
                - LIKWID Metrics: likwid_metrics.md
                - Receive & Display Metrics: metric_receive_display.md
            - Slurm:
                - cc-slurm-adapter: slurm.md
                - cc-slurm-sync: slurm.md
            - Operation & Troubleshooting: operation.md
            - FAQ: faq.md
        - locale: de
          name: Deutsch
          build: true
          nav:
            - Einführung: index.md
            - Monitoring Server:
               - Servervorbereitung: system_preparation.md
               - Server-Komponenten installieren: monitoringserver.md
               - Webinterface: webinterface.md
               - Ersten Cluster anlegen & Subcluster definieren: cluster_setup.md
            - Metriken und Collectoren:
                - cc-metric-collector einrichten: cc_metric_collector_setup.md
                - Quick Setup (Schnellstart): cc_metric_collector_quicksetup.md
                - Schritt-für-Schritt Anleitungen:
                    - Schritt-für-Schritt Erste Metrik: metrics.md
                    - Schritt-für-Schritt Weitere Metriken: more_metrics.md
                - LIKWID Metriken: likwid_metrics.md
                - Metriken empfangen & anzeigen: metric_receive_display.md
            - Slurm:
                - cc-slurm-adapter: slurm_adapter.md
                - cc-slurm-sync: slurm_sync.md
            - Produktivbetrieb: operation.md
            - FAQ: faq.md
  - minify:
      minify_html: true
  - redirects
